# Generated by Django 5.2.8 on 2025-11-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_de_nacimiento', models.DateField()),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=200)),
                ('esPersonal', models.BooleanField()),
                ('esEspectador', models.BooleanField()),
            ],
        ),
    ]
