# Generated by Django 5.2.8 on 2025-11-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkmn_fbdd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='persona',
            table='Persona',
        ),
    ]
