# Generated by Django 5.2.8 on 2025-11-13 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmn_fbdd', '0002_alter_persona_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='esEspectador',
            new_name='esespectador',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='esPersonal',
            new_name='espersonal',
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('esparticipante', models.BooleanField()),
                ('esorganizador', models.BooleanField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pkmn_fbdd.persona')),
            ],
            options={
                'db_table': 'personal',
            },
        ),
    ]
