# Generated by Django 5.2.8 on 2025-11-13 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmn_fbdd', '0003_rename_esespectador_persona_esespectador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='esespectador',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='espersonal',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='personal',
            name='esorganizador',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='personal',
            name='esparticipante',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
