# Generated by Django 5.2.8 on 2025-11-13 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkmn_fbdd', '0004_alter_persona_esespectador_alter_persona_espersonal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='persona',
            field=models.OneToOneField(db_column='persona', on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='pkmn_fbdd.persona'),
        ),
    ]
