--1001 a 2000
insert into Vendedor (id_persona, ubicacion) values (1001, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1002, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1003, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1004, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1005, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1006, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1007, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1008, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1009, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1010, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1011, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1012, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1013, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1014, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1015, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1016, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1017, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1018, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1019, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1020, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1021, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1022, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1023, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1024, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1025, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1026, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1027, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1028, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1029, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1030, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1031, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1032, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1033, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1034, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1035, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1036, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1037, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1038, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1039, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1040, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1041, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1042, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1043, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1044, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1045, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1046, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1047, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1048, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1049, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1050, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1051, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1052, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1053, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1054, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1055, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1056, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1057, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1058, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1059, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1060, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1061, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1062, 'Instituto de Matemáticas');
insert into Vendedor (id_persona, ubicacion) values (1063, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1064, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1065, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1066, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1067, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1068, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1069, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1070, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1071, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1072, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1073, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1074, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1075, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1076, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1077, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1078, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1079, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1080, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1081, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1082, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1083, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1084, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1085, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1086, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1087, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1088, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1089, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1090, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1091, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1092, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1093, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1094, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1095, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1096, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1097, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1098, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1099, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1100, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1101, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1102, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1103, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1104, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1105, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1106, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1107, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1108, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1109, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1110, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1111, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1112, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1113, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1114, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1115, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1116, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1117, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1118, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1119, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1120, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1121, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1122, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1123, 'Frontón Cerrado');
insert into Vendedor (id_persona, ubicacion) values (1124, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1125, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1126, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1127, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1128, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1129, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1130, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1131, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1132, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1133, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1134, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1135, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1136, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1137, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1138, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1139, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1140, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1141, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1142, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1143, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1144, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1145, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1146, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1147, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1148, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1149, 'Instituto de Matemáticas');
insert into Vendedor (id_persona, ubicacion) values (1150, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1151, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1152, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1153, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1154, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1155, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1156, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1157, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1158, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1159, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1160, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1161, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1162, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1163, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1164, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1165, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1166, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1167, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1168, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1169, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1170, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1171, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1172, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1173, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1174, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1175, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1176, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1177, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1178, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1179, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1180, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1181, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1182, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1183, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1184, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1185, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1186, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1187, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1188, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1189, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1190, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1191, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1192, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1193, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1194, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1195, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1196, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1197, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1198, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1199, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1200, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1201, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1202, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1203, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1204, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1205, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1206, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1207, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1208, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1209, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1210, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1211, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1212, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1213, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1214, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1215, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1216, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1217, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1218, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1219, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1220, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1221, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1222, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1223, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1224, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1225, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1226, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1227, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1228, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1229, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1230, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1231, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1232, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1233, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1234, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1235, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1236, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1237, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1238, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1239, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1240, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1241, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1242, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1243, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1244, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1245, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1246, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1247, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1248, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1249, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1250, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1251, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1252, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1253, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1254, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1255, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1256, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1257, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1258, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1259, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1260, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1261, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1262, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1263, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1264, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1265, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1266, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1267, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1268, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1269, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1270, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1271, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1272, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1273, 'Frontón Cerrado');
insert into Vendedor (id_persona, ubicacion) values (1274, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1275, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1276, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1277, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1278, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1279, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1280, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1281, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1282, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1283, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1284, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1285, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1286, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1287, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1288, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1289, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1290, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1291, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1292, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1293, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1294, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1295, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1296, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1297, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1298, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1299, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1300, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1301, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1302, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1303, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1304, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1305, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1306, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1307, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1308, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1309, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1310, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1311, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1312, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1313, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1314, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1315, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1316, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1317, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1318, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1319, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1320, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1321, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1322, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1323, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1324, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1325, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1326, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1327, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1328, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1329, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1330, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1331, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1332, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1333, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1334, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1335, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1336, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1337, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1338, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1339, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1340, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1341, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1342, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1343, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1344, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1345, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1346, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1347, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1348, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1349, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1350, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1351, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1352, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1353, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1354, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1355, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1356, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1357, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1358, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1359, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1360, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1361, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1362, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1363, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1364, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1365, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1366, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1367, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1368, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1369, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1370, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1371, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1372, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1373, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1374, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1375, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1376, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1377, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1378, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1379, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1380, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1381, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1382, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1383, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1384, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1385, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1386, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1387, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1388, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1389, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1390, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1391, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1392, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1393, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1394, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1395, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1396, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1397, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1398, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1399, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1400, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1401, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1402, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1403, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1404, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1405, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1406, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1407, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1408, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1409, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1410, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1411, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1412, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1413, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1414, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1415, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1416, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1417, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1418, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1419, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1420, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1421, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1422, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1423, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1424, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1425, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1426, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1427, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1428, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1429, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1430, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1431, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1432, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1433, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1434, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1435, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1436, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1437, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1438, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1439, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1440, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1441, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1442, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1443, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1444, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1445, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1446, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1447, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1448, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1449, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1450, 'Frontón Cerrado');
insert into Vendedor (id_persona, ubicacion) values (1451, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1452, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1453, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1454, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1455, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1456, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1457, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1458, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1459, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1460, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1461, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1462, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1463, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1464, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1465, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1466, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1467, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1468, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1469, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1470, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1471, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1472, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1473, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1474, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1475, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1476, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1477, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1478, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1479, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1480, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1481, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1482, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1483, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1484, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1485, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1486, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1487, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1488, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1489, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1490, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1491, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1492, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1493, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1494, 'Frontón Cerrado');
insert into Vendedor (id_persona, ubicacion) values (1495, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1496, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1497, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1498, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1499, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1500, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1501, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1502, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1503, 'Instituto de Matemáticas');
insert into Vendedor (id_persona, ubicacion) values (1504, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1505, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1506, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1507, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1508, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1509, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1510, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1511, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1512, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1513, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1514, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1515, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1516, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1517, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1518, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1519, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1520, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1521, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1522, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1523, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1524, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1525, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1526, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1527, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1528, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1529, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1530, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1531, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1532, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1533, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1534, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1535, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1536, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1537, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1538, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1539, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1540, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1541, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1542, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1543, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1544, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1545, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1546, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1547, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1548, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1549, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1550, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1551, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1552, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1553, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1554, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1555, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1556, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1557, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1558, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1559, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1560, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1561, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1562, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1563, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1564, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1565, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1566, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1567, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1568, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1569, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1570, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1571, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1572, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1573, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1574, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1575, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1576, 'Frontón Cerrado');
insert into Vendedor (id_persona, ubicacion) values (1577, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1578, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1579, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1580, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1581, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1582, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1583, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1584, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1585, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1586, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1587, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1588, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1589, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1590, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1591, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1592, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1593, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1594, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1595, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1596, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1597, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1598, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1599, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1600, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1601, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1602, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1603, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1604, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1605, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1606, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1607, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1608, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1609, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1610, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1611, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1612, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1613, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1614, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1615, 'Frontón Cerrado');
insert into Vendedor (id_persona, ubicacion) values (1616, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1617, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1618, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1619, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1620, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1621, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1622, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1623, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1624, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1625, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1626, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1627, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1628, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1629, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1630, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1631, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1632, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1633, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1634, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1635, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1636, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1637, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1638, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1639, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1640, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1641, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1642, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1643, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1644, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1645, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1646, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1647, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1648, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1649, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1650, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1651, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1652, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1653, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1654, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1655, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1656, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1657, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1658, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1659, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1660, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1661, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1662, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1663, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1664, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1665, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1666, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1667, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1668, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1669, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1670, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1671, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1672, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1673, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1674, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1675, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1676, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1677, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1678, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1679, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1680, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1681, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1682, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1683, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1684, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1685, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1686, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1687, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1688, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1689, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1690, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1691, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1692, 'Instituto de Geología');
insert into Vendedor (id_persona, ubicacion) values (1693, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1694, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1695, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1696, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1697, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1698, 'Instituto de Matemáticas');
insert into Vendedor (id_persona, ubicacion) values (1699, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1700, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1701, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1702, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1703, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1704, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1705, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1706, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1707, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1708, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1709, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1710, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1711, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1712, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1713, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1714, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1715, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1716, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1717, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1718, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1719, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1720, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1721, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1722, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1723, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1724, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1725, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1726, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1727, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1728, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1729, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1730, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1731, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1732, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1733, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1734, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1735, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1736, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1737, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1738, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1739, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1740, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1741, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1742, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1743, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1744, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1745, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1746, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1747, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1748, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1749, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1750, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1751, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1752, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1753, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1754, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1755, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1756, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1757, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1758, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1759, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1760, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1761, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1762, 'Escuela Nacional de Enfermería y Obstetricia');
insert into Vendedor (id_persona, ubicacion) values (1763, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1764, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1765, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1766, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1767, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1768, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1769, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1770, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1771, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1772, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1773, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1774, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1775, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1776, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1777, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1778, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1779, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1780, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1781, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1782, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1783, 'Coordinación de Estudios de Posgrado');
insert into Vendedor (id_persona, ubicacion) values (1784, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1785, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1786, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1787, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1788, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1789, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1790, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1791, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1792, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1793, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1794, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1795, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1796, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1797, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1798, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1799, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1800, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1801, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1802, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1803, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1804, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1805, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1806, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1807, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1808, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1809, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1810, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1811, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1812, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1813, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1814, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1815, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1816, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1817, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1818, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1819, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1820, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1821, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1822, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1823, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1824, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1825, 'Frontón Cerrado');
insert into Vendedor (id_persona, ubicacion) values (1826, 'Frontón Cerrado');
insert into Vendedor (id_persona, ubicacion) values (1827, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1828, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1829, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1830, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1831, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1832, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1833, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1834, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1835, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1836, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1837, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1838, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1839, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1840, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1841, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1842, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1843, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1844, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1845, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1846, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1847, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1848, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1849, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1850, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1851, 'Biblioteca Central');
insert into Vendedor (id_persona, ubicacion) values (1852, 'Jardín Botánico');
insert into Vendedor (id_persona, ubicacion) values (1853, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1854, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1855, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1856, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1857, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1858, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1859, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1860, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1861, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1862, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1863, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1864, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1865, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1866, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1867, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1868, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1869, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1870, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1871, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1872, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1873, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1874, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1875, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1876, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1877, 'Instituto de Investigaciones Nucleares');
insert into Vendedor (id_persona, ubicacion) values (1878, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1879, 'Facultad de Odontología');
insert into Vendedor (id_persona, ubicacion) values (1880, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1881, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1882, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1883, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1884, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1885, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1886, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1887, 'Museo de las Ciencias Universum');
insert into Vendedor (id_persona, ubicacion) values (1888, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1889, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1890, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1891, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1892, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1893, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1894, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1895, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1896, 'Instituto de Ciencias Físicas');
insert into Vendedor (id_persona, ubicacion) values (1897, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1898, 'Alberca Olímpica Universitaria');
insert into Vendedor (id_persona, ubicacion) values (1899, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1900, 'Facultad de Economía');
insert into Vendedor (id_persona, ubicacion) values (1901, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1902, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1903, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1904, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1905, 'Estación del Metrobús');
insert into Vendedor (id_persona, ubicacion) values (1906, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1907, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1908, 'Anexo de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1909, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1910, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1911, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1912, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1913, 'Instituto de Investigaciones Filológicas');
insert into Vendedor (id_persona, ubicacion) values (1914, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1915, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1916, 'Facultad de Ciencias');
insert into Vendedor (id_persona, ubicacion) values (1917, 'Frontón Cerrado');
insert into Vendedor (id_persona, ubicacion) values (1918, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1919, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1920, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1921, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1922, 'Museo Universitario Arte Contemporáneo');
insert into Vendedor (id_persona, ubicacion) values (1923, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1924, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1925, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1926, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1927, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1928, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1929, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1930, 'Estación del Pumabús');
insert into Vendedor (id_persona, ubicacion) values (1931, 'Torre de Rectoría');
insert into Vendedor (id_persona, ubicacion) values (1932, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1933, 'Espacio Escultórico');
insert into Vendedor (id_persona, ubicacion) values (1934, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1935, 'Instituto de Biología');
insert into Vendedor (id_persona, ubicacion) values (1936, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1937, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1938, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1939, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1940, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1941, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1942, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1943, 'Facultad de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1944, 'Facultad de Música');
insert into Vendedor (id_persona, ubicacion) values (1945, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1946, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1947, 'Instituto de Investigaciones en Matemáticas Aplicadas');
insert into Vendedor (id_persona, ubicacion) values (1948, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1949, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1950, 'Facultad de Filosofía y Letras');
insert into Vendedor (id_persona, ubicacion) values (1951, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1952, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1953, 'Facultad de Medicina');
insert into Vendedor (id_persona, ubicacion) values (1954, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1955, 'Instituto de Matemáticas');
insert into Vendedor (id_persona, ubicacion) values (1956, 'Instituto de Astronomía');
insert into Vendedor (id_persona, ubicacion) values (1957, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1958, 'Facultad de Arquitectura');
insert into Vendedor (id_persona, ubicacion) values (1959, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1960, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1961, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1962, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1963, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1964, 'Centro Cultural Universitario');
insert into Vendedor (id_persona, ubicacion) values (1965, 'Instituto de Investigaciones Sociales');
insert into Vendedor (id_persona, ubicacion) values (1966, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1967, 'Instituto de Biotecnología');
insert into Vendedor (id_persona, ubicacion) values (1968, 'Facultad de Psicología');
insert into Vendedor (id_persona, ubicacion) values (1969, 'Facultad de Medicina Veterinaria y Zootecnia');
insert into Vendedor (id_persona, ubicacion) values (1970, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1971, 'Facultad de Trabajo Social');
insert into Vendedor (id_persona, ubicacion) values (1972, 'Estadio Olímpico Universitario');
insert into Vendedor (id_persona, ubicacion) values (1973, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1974, 'Instituto de Investigaciones Históricas');
insert into Vendedor (id_persona, ubicacion) values (1975, 'Facultad de Derecho');
insert into Vendedor (id_persona, ubicacion) values (1976, 'Instituto de Fisiología Celular');
insert into Vendedor (id_persona, ubicacion) values (1977, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1978, 'Torre de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1979, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1980, 'Instituto de Química');
insert into Vendedor (id_persona, ubicacion) values (1981, 'Instituto de Investigaciones Estéticas');
insert into Vendedor (id_persona, ubicacion) values (1982, 'Las Islas');
insert into Vendedor (id_persona, ubicacion) values (1983, 'Instituto de Investigaciones Económicas');
insert into Vendedor (id_persona, ubicacion) values (1984, 'Instituto de Investigaciones en Materiales');
insert into Vendedor (id_persona, ubicacion) values (1985, 'Instituto de Ingeniería');
insert into Vendedor (id_persona, ubicacion) values (1986, 'Instituto de Investigaciones en Ecosistemas y Sustentabilidad');
insert into Vendedor (id_persona, ubicacion) values (1987, 'Instituto de Energías Renovables');
insert into Vendedor (id_persona, ubicacion) values (1988, 'Ciclopista del Sur');
insert into Vendedor (id_persona, ubicacion) values (1989, 'Instituto de Investigaciones sobre la Universidad y la Educación');
insert into Vendedor (id_persona, ubicacion) values (1990, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1991, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (1992, 'Instituto de Geofísica');
insert into Vendedor (id_persona, ubicacion) values (1993, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1994, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1995, 'Gimnasio Multidisciplinario');
insert into Vendedor (id_persona, ubicacion) values (1996, 'Instituto de Investigaciones Jurídicas');
insert into Vendedor (id_persona, ubicacion) values (1997, 'Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas');
insert into Vendedor (id_persona, ubicacion) values (1998, 'Instituto de Ecología');
insert into Vendedor (id_persona, ubicacion) values (1999, 'Facultad de Química');
insert into Vendedor (id_persona, ubicacion) values (2000, 'Instituto de Investigaciones Sociales');